In [11]:
import pandas as pd

df = pd.DataFrame([
    ['1', 'Tom', 33, True],
    ['2', 'Bob', 32, False],
    ['3', 'John', 31, False],
])

df.columns = ['id', 'name', 'age', 'decision']
df

id  name  age  decision
0  1   Tom   33      True
1  2   Bob   32     False
2  3  John   31     False

In [12]:
df[['name', 'age']]

name  age
0   Tom   33
1   Bob   32
2  John   31

In [13]:
df.iloc[:, 3]

0     True
1    False
2    False
Name: decision, dtype: bool

In [14]:
df.iloc[1:3, :]

id  name  age  decision
1  2   Bob   32     False
2  3  John   31     False

In [15]:
df[df.age > 32]

id name  age  decision
0  1  Tom   33      True

In [16]:
df[(df.age < 35) & (df.decision == True)]

id name  age  decision
0  1  Tom   33      True

In [18]:
my_matrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(my_matrix)
print(type(my_matrix))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>


In [19]:
my_matrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])